<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "nyssen.me",
    "slogan": "Nyssen, Digital Accessibility Specialist \/ SME",
    "description": "I am a creative freelance web designer &amp; front-end developer specialising in HTML5, CSS3, PWA &amp; WordPress. I design user &amp; SEO friendly websites.",
    "footer": "Copyright \u00a9 2025",
    "itemsPerPage": 6,
    "language": "en",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "Europe\/London",
    "theme": "ny",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "http:\/\/nyssen",
    "emailFrom": "no-reply@nyssen",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "github": "",
    "instagram": "https:\/\/www.instagram.com\/nyssen.me\/",
    "gitlab": "",
    "linkedin": "https:\/\/www.linkedin.com\/in\/sergiduran\/",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "[]"
}