<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "Digital Accessibility Services",
    "slogan": "Nyssen, Digital Accessibility Specialist and Consultant",
    "description": "Digital accessibility specialist with 20+ years in web design and development. WCAG 2.2 AA audits, testing, fixes, accessible documents and team training.",
    "footer": "Copyright \u00a9 2025",
    "itemsPerPage": 6,
    "language": "en",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "Europe\/London",
    "theme": "ny",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "http:\/\/nyssen",
    "emailFrom": "no-reply@nyssen",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "github": "",
    "instagram": "https:\/\/www.instagram.com\/nyssen.me\/",
    "gitlab": "",
    "linkedin": "https:\/\/www.linkedin.com\/in\/sergiduran\/",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "{\r\n    &quot;subtitle&quot;: {\r\n        &quot;type&quot;: &quot;string&quot;,\r\n        &quot;label&quot;: &quot;Subtitle&quot;,\r\n        &quot;placeholder&quot;: &quot;Subtitle for the page&quot;\r\n    },\r\n    &quot;externalUrl&quot;: {\r\n        &quot;type&quot;: &quot;string&quot;,\r\n        &quot;label&quot;: &quot;External URL&quot;,\r\n        &quot;tip&quot;: &quot;Optional. If filled, the resources list links here instead of to the page.&quot;,\r\n        &quot;placeholder&quot;: &quot;https:\\\/\\\/example.com&quot;\r\n    }\r\n}"
}